name: flutter_graphql_sample
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:

  # Architecture
  flutter_riverpod: ^1.0.0

  # Graphql Client
  graphql: ^5.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

  # Model Generator
  freezed: ^0.14.0
  freezed_annotation: ^0.15.0

  # File Generator
  build_runner: ^2.1.11

  # Graphql Generator
  gql_build: ^0.4.1

  # JSON Handler
  json_serializable: ^6.2.0
